server:
  port: 9001
spring:
  application:
    name: demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.99.243.32:3306/tigrex?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: tigrex
      password: 123456
